### ISSUE TITLE
Lỗi THP/TDP và thêm chức năng cướp tiêu

### ISSUE THREAD

**Issue by DraBoyTh** [vinh-ttn/vantieu9#1]
-Tạo npc player đánh được tiêu chính mình
-khi di chuyển bằng thp hoặc thổ địa phù đều mang npc cùng, theo nguyên bản nó chỉ add khi player đạp trap

**Comment by vinh-ttn** [comment]
@DraBoyTh 
> theo nguyên bản nó chỉ add khi player đạp trap

Nếu bộ này có chức năng đạp trap thì có nghĩa là bộ này share bị thiếu rồi

Vì trong  [file hành trình](https://github.com/vinh-ttn/vantieu9/blob/main/server1/settings/event/longmenbiaoju/route.txt) chỉ thấy khai báo đường đi từ thành này qua thành kia chứ không có khai báo tọa độ của trap để đạp lên

Có e cách giải quyết:

1) Chờ AE nào đó làm tọa độ trap cho từng hành trình trong file trên

2) Thêm vào chức năng chỉ cho tiêu qua map khi map đang đến là map trả tiêu. 

3) Thêm vào chức năng cấp xài THP (và TDP?) khi đang có tiêu. Giống như đang trong Tống Kim không thể xài vậy.


Cách 2 thì dễ nhưng vẫn sẽ dính lỗi THP (nghĩa là phù ngay qua map trả tiêu là xong). Hoặc nó sẽ không hoạt động khi hành trình yêu cầu đi qua map thứ 3 mới tới map trả tiêu (Ví dụ hành trình Tương Dương -> Dương Châu sẽ cần đi qua map Đạo Hương Thôn chẳng hạn; thì tiêu sẽ không thể qua map Đạo Hương Thôn; vì nó không phải điểm cuối của map hành trình). 

Cho nên cách giải quyết 1 và 3 vẫn là đúng nhất.

**Comment by vinh-ttn** [comment]
đã sửa lỗi qua map = giải pháp thứ 3 (tắt TDP và THP) trong [commit](https://github.com/vinh-ttn/vantieu9/commit/d23b19577b11d5e0fcd207d79931a64555a917f6)

và cập nhật chi tiết event trên trang chính
